### ISSUE TITLE
The logued device ID doesn't match the data 

### ISSUE THREAD

**Issue by geilsonrm** [aerosales10/nest-gps-server#1] opened 2020-06-17 03:12 UTC
Hello, if I do the test with just one tracker, it seems to work normal ...

If I use two trackers, nest-gps-server seems to treat both as if it were just an instance and causes an error:

``
[868683029084948] [127.0.0.1:54459] The logued device ID doesn't match the data ID [868683029084948]
``

Can you help me?

**Comment by aerosales10** [comment] 2020-06-17 16:58
Hi @geilsonrm I would be glad to help you. Can you please give me a more detailed example or the data you are using for tenting so that I can reproduce the issue?

**Comment by geilsonrm** [comment] 2020-06-17 17:55
Hi @aerosales10 

Thank you very much for your feedback!

I can upload an example to share. But first let me resolve a question:

Each tracker that opens a new connection, should I control these instances or does nest-gps-server do this control for me?

I am confused because I simulated two connections using the Echo adapter:

Client_A and Client_B send packets, but client_A is receiving responses for it and is also receiving responses that would be for Client_B.

Client_B is left with no answers.

```
@Module({
  imports: [GpsServerModule.forRoot({
    port: 5008,
    adapter: Echo
  })],
  controllers: [AppController],
  providers: [AppService],
})  
```

**Comment by aerosales10** [comment] 2020-06-17 18:07
Hi @geilsonrm the server should reply only to the client that is sending the packets. Until now the tests have been done only with one tracker. Each server maintains a list of connections and each connection has an adapter. I will do some testing simulating more than one tracker.

**Comment by geilsonrm** [comment] 2020-06-17 18:48
I love the package, your implementation is perfect, I intend to create adapters for Suntech and other manufacturers.

The only problem I found was this, testing with only one tracker works well, more than one tracker it answers all to the same client.

I look forward to moving forward with the project, I look forward to it. Thank you!

**Comment by aerosales10** [comment] 2020-06-17 19:02
Thank you, I'm happy that you can use it.
The Echo protocol adapter has the device_id hard-coded so it only supports one Echo tracker (it was build to testing), This behaviour will be changed by generating a random  ID for each connection adding support for multiple Echo trackers.
For this specific issue I will need more data and the adapter you are using:

> Hello, if I do the test with just one tracker, it seems to work normal ...
> 
> If I use two trackers, nest-gps-server seems to treat both as if it were just an instance and causes an error:
> 
> `[868683029084948] [127.0.0.1:54459] The logued device ID doesn't match the data ID [868683029084948]`
> 
> Can you help me?

**Comment by geilsonrm** [comment] 2020-06-17 20:18
@aerosales10 

I am creating a custom adapter and I have the same problem reported.

Here is an example:

``
@Injectable ()
export class ST300 implements GpsAdapterInterface {
         device: AbstractGpsDevice;

}
``

Could you tell me which adapter works correctly with more than one tracker for me to test?

**Comment by aerosales10** [comment] 2020-06-17 20:37
Ok GPS103 works for me with multiple trackers. Be aware that in the current GPS103 adapter the device_id is set to the IMEI that must be present in each message. Some examples that you can test:
Device 1:
Login:
##,imei:334552367856446,A;
Hearthbeat:
334552367856446
PING:
imei:334552367856446,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;
Device 2:
Login:
##,imei:334552367856447,A;
Hearthbeat:
334552367856447
PING:
imei:334552367856447,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;

If the ST300 protocol does not have a device_id yo can check the recently implemented Echo protocol that uses remote IP and remote port as device_id:
```typescript
async parse_data(data: string | Buffer): Promise<GpsMessagePartsInterface> {
        let str_data = data.toString().trim();
        let response = {
            action: GPS_MESSAGE_ACTION.PING,
            cmd: "Echo",
            data: str_data,
            // The device_id is needed by the server and should be unique for each tracker
            device_id: `${this.device.ip}-${this.device.port}` 
        };

        if (str_data == "login")
            response.action = GPS_MESSAGE_ACTION.LOGIN_REQUEST;

        return response;
    }
```

**Comment by geilsonrm** [comment] 2020-06-18 15:30
I did the test with the GPS103 adapter and had the same problem.

If I just call client01 everything is ok!
If I just call client02 all ok!
If I call client01 and client 02 the problem happens.

See below the steps I followed and the result:

```typescript
// app.module.ts

@Module ({
  imports: [GpsServerModule.forRoot ({
    port: 5008,
    adapter: GPS103
  })],
  controllers: [AppController],
  providers: [AppService],
})
```

```typescript
// client01.js

const net = require ('net');
const intervals = [];
const clients = [];

clients [0] = new net.Socket ();

clients [0] .connect (5008, '127.0.0.1', () => {
  console.clear ()
  console.log (Date ())
  console.log ('Connected');
clients [0] .write ('##, imei: 222222222222222, A;');

intervals [0] = setInterval (() => {clients [0] .write ('222222222222222')}, 4000);

intervals [1] = setInterval (() => {
clients [0] .write ('imei: 222222222222222,001,0809231929,13554900601, F, 055403.000, A, 2233.1870, N, 11354.3067, E, 0.00,30.1,65.43,1,0,10.5%, 0.0%, 28; ');
}, 8000);

});


clients [0] .on ('data', (data) => {console.log ('Received:' + data)});

clients [0] .on ('close', () => {
clearInterval (intervals [0])
clearInterval (intervals [1])
console.log ('Connection closed by server')
});

setTimeout (() => {
console.log ('Connection closed by client')
clients [0] .destroy ()
}, 20000);
```


```typescript
// client02.js

const net = require('net');
const intervals = [];
const clients = [];

clients[0] = new net.Socket();
clients[1] = new net.Socket();

clients[0].connect(5008, '127.0.0.1', () => {
  console.clear()
  console.log(Date())
  console.log('Connected');
	clients[0].write('##,imei:333333333333333,A;');

	intervals[0] = setInterval(() => { clients[0].write('333333333333333')}, 4000);

	intervals[1] = setInterval(() => {
		clients[0].write('imei:333333333333333,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;');
	}, 8000);
	
});


clients[0].on('data', (data) => { console.log('Received: ' + data) });

clients[0].on('close', () => { 
	clearInterval(intervals[0])
	clearInterval(intervals[1])
	console.log('Connection closed by server') 
});

setTimeout(() => { 

	console.log('Connection closed by client') 
	clients[0].destroy()
}, 20000);
```

```properties
[Nest] 26844 - 2020-06-18 12:12:31 Incomming connection from 127.0.0.1:59004 + 17773ms
[Nest] 26844 - 2020-06-18 12:12:31 Incomming connection from 1 + 3ms
[Nest] 26844 - 2020-06-18 12:12:31 Device 222222222222222 has been authorized. + 33ms
[Nest] 26844 - 2020-06-18 12:12:34 Incomming connection from 127.0.0.1:59006 + 2355ms
[Nest] 26844 - 2020-06-18 12:12:34 Incomming connection from 2 + 1ms
[Nest] 26844 - 2020-06-18 12:12:34 Device 333333333333333 has been authorized. + 15ms
[Nest] 26844 - 2020-06-18 12:12:35 [222222222222222] [127.0.0.1:59004] The logued device ID doesn't match the data ID [222222222222222] + 1621ms
[Nest] 26844 - 2020-06-18 12:12:39 [222222222222222] [127.0.0.1:59004] The logued device ID doesn't match the data ID [222222222222222] + 4000ms
[Nest] 26844 - 2020-06-18 12:12:39 [222222222222222] [127.0.0.1:59004] The logued device ID doesn't match the data ID [222222222222222] + 5ms
[Nest] 26844 - 2020-06-18 12:12:42 Position received (22.33187, 113.543067) Tue Sep 23 2008 05:54:03 GMT-0300 (GMT-03: 00) + 2386ms
[Nest] 26844 - 2020-06-18 12:12:43 [222222222222222] [127.0.0.1:59004] The logued device ID doesn't match the data ID [222222222222222] + 1624ms
[Nest] 26844 - 2020-06-18 12:12:47 [222222222222222] [127.0.0.1:59004] The logued device ID doesn't match the data ID [222222222222222] + 3987ms
[Nest] 26844 - 2020-06-18 12:12:47 [222222222222222] [127.0.0.1:59004] The logued device ID doesn't match the data ID [222222222222222] + 15ms
[Nest] 26844 - 2020-06-18 12:12:50 Position received (22.33187, 113.543067) Tue Sep 23 2008 05:54:03 GMT-0300 (GMT-03: 00) + 2383ms
[Nest] 26844 - 2020-06-18 12:12:51 Device 127.0.0.1:59004 disconnected. + 1586ms
[Nest] 26844 - 2020-06-18 12:12:54 Device 127.0.0.1:59006 disconnected. + 2396ms
```

**Comment by aerosales10** [comment] 2020-06-18 15:35
Hi @geilsonrm, I will try to reproduce today these tests you have made. Thanks

**Comment by geilsonrm** [comment] 2020-06-18 16:10
@aerosales10 Whenever a customer communicates, he always considers the device of the last customer who logged in.

Unlike the client that terminates the connection, and it identifies the client correctly before removing it from devices:

```typescript
// gps-tcp-server.service.ts

device.on('disconnect', (uid) => {
    let index = self.devices.findIndex((device: AbstractGpsDevice, index: number) => {
        if (device.getUID() === uid) {
            self.devices.splice(index, 1);
            return true;
        }
    });
    if (index < 0) return;
    self.logger.debug(`Device ${device.ip}:${device.port} disconnected.`);
    device.emit('disconnected');
});
```

**Comment by aerosales10** [comment] 2020-06-18 20:09
> @aerosales10 Whenever a customer communicates, he always considers the device of the last customer who logged in.
> 
> Unlike the client that terminates the connection, and it identifies the client correctly before removing it from devices:
> 
> ```ts
> // gps-tcp-server.service.ts
> 
> device.on('disconnect', (uid) => {
>     let index = self.devices.findIndex((device: AbstractGpsDevice, index: number) => {
>         if (device.getUID() === uid) {
>             self.devices.splice(index, 1);
>             return true;
>         }
>     });
>     if (index < 0) return;
>     self.logger.debug(`Device ${device.ip}:${device.port} disconnected.`);
>     device.emit('disconnected');
> });
> ```

Hi @geilsonrm, I have verified the issue and indeed happens with the test case that you have sent me. In the adapter I'm receiving this string "334552367856440 imei:334552367856440,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28; 334552367856440" which it is not correct or expected. I'm still trying to find what is causing it.

**Comment by geilsonrm** [comment] 2020-06-18 20:47
If you put a console.log to show the socket port, can you see that it is different from the adapter port, and it should be the same correct?

```typescript
// gps-tcp-server.service.ts

socket.on('data', (data) => {

    console.log ('Port socket:', socket.remotePort) 

    device.emit('data', data)
});
```

```typescript
    if (heartbeat_test) {
        let groups = heartbeat_test.groups;
        parts.device_id = groups['IMEI'];

        console.log ('Port adapter:', this.device.port) 

        if (this.device.loged && this.device.getUID() != parts.device_id) 
        throw `The logued device ID doesn't match the data ID[${parts.device_id}]`;
        parts.cmd = "heartbeat";
        parts.action = GPS_MESSAGE_ACTION.OTHER;
        return parts;
}
```

![image](https://user-images.githubusercontent.com/10155481/85069943-5867f580-b18b-11ea-91b6-8a4b5edba001.png)

The adapter always uses the same instance as the last client that made a new connection, it remains to pass the equivalent instance to the client.

**Comment by aerosales10** [comment] 2020-06-18 21:29
This should fix the GPS103 adapter. It was tested with the same provided data and an aditional non authenticated device.
Here are some debug logs:
```shell
[Nest] 4437   - 06/18/2020, 9:26:00 PM   Incomming connection from 127.0.0.1:50614 +102243ms
[Nest] 4437   - 06/18/2020, 9:26:00 PM   Incomming connection from 127.0.0.1:50616 +2ms
[Nest] 4437   - 06/18/2020, 9:26:00 PM   Incomming connection from 127.0.0.1:50618 +1ms
[Nest] 4437   - 06/18/2020, 9:26:00 PM   [undefined]Receiving raw data: ##,imei:334552367856440,A;
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:00 PM   Device 334552367856440 has been authorized. +1ms
[Nest] 4437   - 06/18/2020, 9:26:00 PM   [undefined]Receiving raw data: ##,imei:334552367856441,A;
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:00 PM   Device 334552367856441 has been authorized. +1ms
[Nest] 4437   - 06/18/2020, 9:26:04 PM   [334552367856440]Receiving raw data: 334552367856440
 +3987ms
[Nest] 4437   - 06/18/2020, 9:26:04 PM   [undefined]Receiving raw data: 334552367856444
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:04 PM   334552367856444 is trying to OTHER but isn't logged. Action wasn't executed. +0ms
[Nest] 4437   - 06/18/2020, 9:26:04 PM   [334552367856441]Receiving raw data: 334552367856441
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:07 PM   [334552367856440]Receiving raw data: imei:334552367856440,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;
 +2997ms
[Nest] 4437   - 06/18/2020, 9:26:07 PM   [334552367856440]Position received ( 22.33187, 113.543067 ) Tue Sep 23 2008 05:54:03 GMT+0000 (GMT) +3ms
[Nest] 4437   - 06/18/2020, 9:26:07 PM   [334552367856441]Receiving raw data: imei:334552367856441,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%, 28;
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:07 PM   [334552367856441]Position received ( 22.33187, 113.543067 ) Tue Sep 23 2008 05:54:03 GMT+0000 (GMT) +1ms
[Nest] 4437   - 06/18/2020, 9:26:07 PM   [334552367856444]Receiving raw data: imei:334552367856444,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:07 PM   334552367856444 is trying to PING but isn't logged. Action wasn't executed. +1ms
[Nest] 4437   - 06/18/2020, 9:26:08 PM   [334552367856440]Receiving raw data: 334552367856440
 +995ms
[Nest] 4437   - 06/18/2020, 9:26:08 PM   [334552367856444]Receiving raw data: 334552367856444
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:08 PM   334552367856444 is trying to OTHER but isn't logged. Action wasn't executed. +2ms
[Nest] 4437   - 06/18/2020, 9:26:08 PM   [334552367856441]Receiving raw data: 334552367856441
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:12 PM   [334552367856444]Receiving raw data: 334552367856444
 +3997ms
[Nest] 4437   - 06/18/2020, 9:26:12 PM   334552367856444 is trying to OTHER but isn't logged. Action wasn't executed. +1ms
[Nest] 4437   - 06/18/2020, 9:26:12 PM   [334552367856440]Receiving raw data: 334552367856440
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:12 PM   [334552367856441]Receiving raw data: 334552367856441
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:14 PM   [334552367856440]Receiving raw data: imei:334552367856440,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;
 +1993ms
[Nest] 4437   - 06/18/2020, 9:26:14 PM   [334552367856440]Position received ( 22.33187, 113.543067 ) Tue Sep 23 2008 05:54:03 GMT+0000 (GMT) +2ms
[Nest] 4437   - 06/18/2020, 9:26:14 PM   [334552367856444]Receiving raw data: imei:334552367856444,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%,28;
 +1ms
[Nest] 4437   - 06/18/2020, 9:26:14 PM   334552367856444 is trying to PING but isn't logged. Action wasn't executed. +1ms
[Nest] 4437   - 06/18/2020, 9:26:14 PM   [334552367856441]Receiving raw data: imei:334552367856441,001,0809231929,13554900601,F,055403.000,A,2233.1870,N,11354.3067,E,0.00,30.1,65.43,1,0,10.5%,0.0%, 28;
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:14 PM   [334552367856441]Position received ( 22.33187, 113.543067 ) Tue Sep 23 2008 05:54:03 GMT+0000 (GMT) +1ms
[Nest] 4437   - 06/18/2020, 9:26:16 PM   [334552367856444]Receiving raw data: 334552367856444
 +1999ms
[Nest] 4437   - 06/18/2020, 9:26:16 PM   334552367856444 is trying to OTHER but isn't logged. Action wasn't executed. +1ms
[Nest] 4437   - 06/18/2020, 9:26:16 PM   [334552367856440]Receiving raw data: 334552367856440
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:16 PM   [334552367856441]Receiving raw data: 334552367856441
 +2ms
[Nest] 4437   - 06/18/2020, 9:26:20 PM   Device 127.0.0.1:50618 disconnected. +3992ms
[Nest] 4437   - 06/18/2020, 9:26:20 PM   Device 127.0.0.1:50614 disconnected. +2ms
[Nest] 4437   - 06/18/2020, 9:26:20 PM   Device 127.0.0.1:50616 disconnected. +1ms
```

**Comment by aerosales10** [comment] 2020-06-18 21:45
> If you put a console.log to show the socket port, can you see that it is different from the adapter port, and it should be the same correct?
> 
> ```ts
> // gps-tcp-server.service.ts
> 
> socket.on('data', (data) => {
> 
>     console.log ('Port socket:', socket.remotePort) 
> 
>     device.emit('data', data)
> });
> ```
> 
> ```ts
>     if (heartbeat_test) {
>         let groups = heartbeat_test.groups;
>         parts.device_id = groups['IMEI'];
> 
>         console.log ('Port adapter:', this.device.port) 
> 
>         if (this.device.loged && this.device.getUID() != parts.device_id) 
>         throw `The logued device ID doesn't match the data ID[${parts.device_id}]`;
>         parts.cmd = "heartbeat";
>         parts.action = GPS_MESSAGE_ACTION.OTHER;
>         return parts;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/10155481/85069943-5867f580-b18b-11ea-91b6-8a4b5edba001.png)
> 
> The adapter always uses the same instance as the last client that made a new connection, it remains to pass the equivalent instance to the client.

Reopened, needs more debugging. It's seems that the adapters are sharing the same socket, only one client receive the responses.

**Comment by aerosales10** [comment] 2020-06-18 22:13
@geilsonrm The factory was a service and in nestjs all services by default are singletons. The same adapter instance was passed to each device. Now is fixed. Let me know if you have any more issues.

**Comment by geilsonrm** [comment] 2020-06-18 23:24
> @geilsonrm The factory was a service and in nestjs all services by default are singletons. The same adapter instance was passed to each device. Now is fixed. Let me know if you have any more issues.

The bug was correct, I am very happy with your dedication.

I will open a new issue (this time something simpler), I hope not to bother.

This issue can now be finalized. Thank you very much!

**Comment by aerosales10** [comment] 2020-06-19 19:50
I'm glad to help. Closing the issue.

**Closed by aerosales10** 2020-06-19 19:50 UTC
Labels: bug
